# Generated by Django 4.1.7 on 2023-03-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ang',
            field=models.DecimalField(decimal_places=20, max_digits=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='lon',
            field=models.DecimalField(decimal_places=20, max_digits=200),
        ),
    ]
