# Generated by Django 4.1.7 on 2023-03-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_alter_data_ang_alter_data_lat_alter_data_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='_id',
        ),
    ]
